# Generated by Django 5.2.4 on 2025-07-26 13:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfile',
            name='file',
            field=models.FileField(upload_to=core.models.order_file_upload_path),
        ),
    ]
